- name: mkdir confdir and ssl
  file: path={{ item }} state=directory
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/ssl

- name: "edit config"
  template: src=etc/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: put upstart script
  template: src=etc/init/nginx.conf.j2 dest=/etc/init/nginx.conf owner=root group=root mode=0644
  changed_when: true
  notify:
    - restart nginx
