- name: add group 
  group: name={{ nginx_user }} gid=48

- name: add user
  user: name={{ nginx_user }} uid=48 group={{ nginx_group }} home=/var/nginx

- name: "install dependence packages"
  yum: name={{ item }} state=latest
  with_items:
    - openssl-devel
    - pcre-devel

- name: "wget nginx package"
  get_url: url={{ nginx_src_url }} dest=/var/tmp

- name: "expand nginx"
  command: tar xzvf nginx-{{ nginx_version }}.tar.gz chdir=/var/tmp

- name: "install nginx"
  shell: | 
    ./configure {{ nginx_compile_option }} &&
    make &&
    make install
    chdir=/var/tmp/nginx-{{ nginx_version }}
