- name: get currently installed nginx version
  shell: "{{ nginx_symlink }}/sbin/nginx -v"
  register: result
  always_run: yes
  ignore_errors: True

- include: install_from_src.yml
  when: result.get('stderr') != 'nginx version{{ colon }} nginx/{{ nginx_version }}'

- include: configure.yml
  notify: restart nginx
